### ISSUE TITLE
【我的推广】功能无效

### ISSUE THREAD

**Issue by LouisLiu00** [Guoqing815/litchi.ai#1]
我已经使用推广链接推荐了新用户并成功注册登录，但显示“还没有邀请记录”，以及对应的 Token 奖励也未发放！

 [www.brath.cn/#/WeChatLogin?referral=f89c865f1d933c82433b4e703fa9a4d7](url)

**Comment by Guoqing815** [comment]
@LouisLiu00 收到异常，我会在新版本发布时同时Fix，请记录用户ID以获取Token奖励补偿。
